# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tile.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntile.proto\x12\x16hardware_matrix_decomp\"+\n\nTensorData\x12\x0e\n\x06values\x18\x01 \x03(\x02\x12\r\n\x05shape\x18\x02 \x03(\x05\"k\n\x0bTileRequest\x12\x36\n\nactivation\x18\x01 \x01(\x0b\x32\".hardware_matrix_decomp.TensorData\x12\x0f\n\x07tile_id\x18\x02 \x01(\t\x12\x13\n\x0bsequence_id\x18\x03 \x01(\x05\"h\n\x0cTileResponse\x12\x32\n\x06output\x18\x01 \x01(\x0b\x32\".hardware_matrix_decomp.TensorData\x12\x0f\n\x07tile_id\x18\x02 \x01(\t\x12\x13\n\x0bsequence_id\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSORDATA']._serialized_start=38
  _globals['_TENSORDATA']._serialized_end=81
  _globals['_TILEREQUEST']._serialized_start=83
  _globals['_TILEREQUEST']._serialized_end=190
  _globals['_TILERESPONSE']._serialized_start=192
  _globals['_TILERESPONSE']._serialized_end=296
# @@protoc_insertion_point(module_scope)
